#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : python-swiftclient
Version  : 3.1.0
Release  : 27
URL      : http://tarballs.openstack.org/python-swiftclient/python-swiftclient-3.1.0.tar.gz
Source0  : http://tarballs.openstack.org/python-swiftclient/python-swiftclient-3.1.0.tar.gz
Source99 : http://tarballs.openstack.org/python-swiftclient/python-swiftclient-3.1.0.tar.gz.asc
Summary  : OpenStack Object Storage API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-swiftclient-bin
Requires: python-swiftclient-python
Requires: python-swiftclient-doc
Requires: futures
Requires: python-keystoneclient
Requires: requests
Requires: six
BuildRequires : docutils
BuildRequires : futures-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : testrepository-python
BuildRequires : tox
BuildRequires : virtualenv

%description
Python bindings to the OpenStack Object Storage API
===================================================

%package bin
Summary: bin components for the python-swiftclient package.
Group: Binaries

%description bin
bin components for the python-swiftclient package.


%package doc
Summary: doc components for the python-swiftclient package.
Group: Documentation

%description doc
doc components for the python-swiftclient package.


%package python
Summary: python components for the python-swiftclient package.
Group: Default

%description python
python components for the python-swiftclient package.


%prep
%setup -q -n python-swiftclient-3.1.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487899547
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test || :
%install
export SOURCE_DATE_EPOCH=1487899547
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/swift

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
